Get  http://localhost:3001/cidades



###
GET http://localhost:3001/listar-dados


###
GET http://localhost:3001/estados

###
GET  http://localhost:3001/cidades/bahia

###
GET  http://localhost:3001/consultar/bahia/salvador

###
GET http://localhost:3001/consultar/10002


###
POST http://localhost:3001/login
Content-Type: application/json
Accept: "*/*"

{"user": "admin", 
"pass": "1234"}

