Get  http://localhost:3001/cidades



###
GET http://localhost:3001/listar-dados


###
GET http://localhost:3001/estados

###
GET  http://localhost:3001/cidades/bahia

###
GET  http://localhost:3001/consultar/bahia/salvador

###
GET http://localhost:3001/consultar/10002


###
POST http://localhost:3001/login
Content-Type: application/json
Accept: "*/*"

{"user": "admin", 
"pass": "1234"}




#######################################
## production
######################################

###
GET https://align-api.onrender.com/estados

###
GET  https://align-api.onrender.com/cidades/são paulo

###
GET  https://align-api.onrender.com/consultar/bahia/salvador

###
GET https://align-api.onrender.com/consultar/70109

###
GET http://align-api.onrender.com/listar-dados